repository: dynamsoft-docs/mobile-document-scanner-docs-js
repositoryUrl: https://github.com/dynamsoft-docs/mobile-document-scanner-docs-js/blob/main
docFullPath: https://www.dynamsoft.com/mobile-document-scanner/docs/web
firstLevelUrl: /mobile-document-scanner/docs/web
docHomePage: /mobile-document-scanner/docs/web/introduction/

introduction: /mobile-document-scanner/docs/web/introduction/
gettingstarted: /mobile-document-scanner/docs/web/gettingstarted/
codegallery: /mobile-document-scanner/docs/web/codegallery/
code-gallery: /mobile-document-scanner/docs/web/code-gallery/
api: /mobile-document-scanner/docs/web/api/

guide: /mobile-document-scanner/docs/web/guide/

release-notes: /mobile-document-scanner/docs/web/release-notes/

useVersionTree: true

assets: /mobile-document-scanner/docs/web/assets/
edit_icon: /mobile-document-scanner/docs/web/assets//img-icon/edit-icon.png
smile_icon: /mobile-document-scanner/docs/web/assets/img-icon/icon-smile.png
sad_icon: /mobile-document-scanner/docs/web/assets/img-icon/icon-sad.png

baseurl: "/mobile-document-scanner/docs/web"

download: "/mobile-document-scanner/downloads/"

plugins:
  - jemoji
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
